<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'dazn1.de',
  'creator_name' => 'Alex',
  'creation_date' => '2022-04-15',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Berlin',
  'culture' => 'de',
  'max_day' => '10',
  'episodeOption' => '1',
  'url1' => 'https://www.sky.de/sgtvg/service/getBroadcasts',
  'requestOption1' => '2',
  'post_data1' => '{"d":##urldate1##,"lt":6,"t":0,"s":0,"pn":1,"sto":10,"epp":16,"cil":[##channel##]}',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'content_type1' => 'application/json;charset=UTF-8',
  'referer_header1' => 'https://www.sky.de/tvguide/dazn-1-hd-c659',
  'origin_header1' => 'https://www.sky.de',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'java',
  'show' => '{"cn":(.*?)}',
  'start' => 'bst":"(.*?)"',
  'start_format' => 'H:i',
  'duration' => '"len":(.*?),"',
  'title' => '"et":"(.*?)"',
  'subtitle' => '"epit":"(.*?)"',
  'category' => '"ec":"(.*?)"',
  'production_date' => '"yop":(.*?),',
  'country' => '"cop":"(.*?)"',
  'rating' => '"fsk":"ab (.*?) Jahr',
  'ccurl1' => 'https://www.sky.de/sgtvg/service/getChannelList',
  'ccrequestOption1' => '2',
  'ccpost_data1' => '{"dom":"de","s":0,"feed":1}',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccorigin_header1' => 'https://www.sky.de',
  'ccXMLHttpRequest1' => 'on',
  'ccchannel_block' => '{"(.*?)},',
  'ccchannel_id' => 'ci":(.*?),',
  'ccchannel_name' => '"cn":"(.*?)"',
);
?>