<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'horizon.de',
  'creator_name' => 'Alex',
  'creation_date' => '2022-10-04',
  'rev_no' => 'R0',
  'timezone' => '+02:00',
  'culture' => 'de',
  'max_day' => '14',
  'episodeOption' => '1',
  'url1' => 'https://legacy-dynamic.oesp.horizon.tv/oesp/v4/DE/deu/web/listings?byEndTime=##urldate1##~&byLocationId=65535&byResolutions=SD%2CHD&byStationId=lgi-obolite-de-prod-master%3A##channel##&range=1-250&sort=startTime',
  'requestOption1' => '1',
  'accept_header1' => 'application/json',
  'content_type1' => 'application/json',
  'referer_header1' => 'https://www.horizon.tv/',
  'host_header1' => 'legacy-dynamic.oesp.horizon.tv',
  'origin_header1' => 'https://www.horizon.tv',
  'urldate_format1' => 'java',
  'stopdate_format1' => 'java',
  'show' => '"id":"crid:~~2F(.*?)ViaExternalApp"',
  'start' => '"startTime":(.*?),',
  'start_format' => 'java',
  'stop' => '"endTime":(.*?),',
  'stop_format' => 'java',
  'title' => '~~\\w*","title":"(.*?)","description',
  'subtitle' => '"secondaryTitle":"(.*?)"',
  'desc' => '"longDescription":"(.*?)"',
  'category' => 'lgi-obolite-de-prod-master:genre-\\d*","title":"(.*?)"',
  'showicon' => '"url":"(.*?)"\\}||#max#1',
  'season' => '"seriesNumber":"(\\d{1,3})"',
  'episode' => '"seriesEpisodeNumber":"(\\d{1,3})"',
  'channel_logo' => '||#add###cclogo##',
  'production_date' => '"year":"(.*?)"',
  'actor' => '"cast":\\["(.*?)"\\],||#split#(",")',
  'director' => '"directors":\\["(.*?)"\\],||#replace#(",")||, ',
  'rating' => '"parentalRating":"(.*?)"||#addend#+',
  'ccurl1' => 'https://legacy-dynamic.oesp.horizon.tv/oesp/v4/DE/deu/web/channels?byLocationId=65535&includeInvisible=true&personalised=false&sort=channelNumber&withStationResolutions=SD%2CHD',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json;charset=UTF-8',
  'ccorigin_header1' => 'https://www.horizon.tv',
  'ccchannel_block' => '\\{"id":"lgi-obolite-de-prod-master:\\d(.*?)"station-logo-medium"',
  'ccchannel_id' => '\\{"station":\\{"id":"lgi-obolite-de-prod-master:(.*?)","',
  'ccchannel_name' => 'locationId":"\\d*","title":"(.*?)","',
  'ccchannel_logo' => 'station-logo-large"],"url":"(.*?)\\\\?style',
);
?>