<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'live.tvspielfilm.de ',
  'creator_name' => 'Alex',
  'creation_date' => '2022-04-16',
  'rev_no' => 'R0',
  'timezone' => '+01:00',
  'culture' => 'de',
  'max_day' => '14',
  'rating_system' => 'FSK',
  'episodeOption' => '1',
  'url1' => 'https://live.tvspielfilm.de/static/broadcast/list/##channel##/##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'urldate_format1' => 'Y-m-d',
  'show' => '"hexId"(.*?)"id"|"hexId"(.*?)}]\\s',
  'start' => '"timestart":(.*?),',
  'start_format' => 'unix',
  'stop' => '"timeend":(.*?),',
  'stop_format' => 'unix',
  'title' => 'start":\\d*,"title":"(.*?)"',
  'subtitle' => '"episodeTitle":"(.*?)"',
  'desc' => '"text":"(.*?)\\(Senderinfo\\)|"text":"(.*?)","||#replace#(Infos zur Serie:)||',
  'category' => '"genre":"(.*?)"',
  'showicon' => '"size4":"(.*?)"}||#max#1',
  'season' => '"seasonNumber":"(\\d*)"',
  'episode' => '"episodeNumber":"(\\d*)\\/',
  'channel_logo' => '||#add###cclogo##',
  'production_date' => '"year":(\\d{4})',
  'actor' => '"actors":\\[{"(.*?)"}]||#replace#("},{")##(":")||, ##: ||#split#(,) ',
  'director' => '"director":"(.*?)"',
  'presenter' => '"anchorman":"(.*?)",',
  'guest' => '"studio_guests":\\["(.*?)"\\]',
  'country' => '"country":"(.*?)"',
  'rating' => '"fsk":(.*?),"||#addend#+',
  'ccurl1' => 'https://live.tvspielfilm.de/static/content/channel-list/livetv',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'ccchannel_block' => '{"i(.*?)}}',
  'ccchannel_id' => '"id":"(.*?)"',
  'ccchannel_name' => '"name":"(.*?)"',
);
?>