<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'magenta.at',
  'creator_name' => 'Alex',
  'creation_date' => '2022-03-23',
  'rev_no' => 'R0',
  'timezone' => '+02:00',
  'culture' => 'de',
  'max_day' => '14',
  'rating_system' => 'FSK:',
  'episodeOption' => '1',
  'url1' => 'https://prod.oesp.magentatv.at/oesp/v4/AT/deu/web/listings?byEndTime=##urldate1##~&byLocationId=101&byResolutions=SD%2CHD&byStationId=lgi-at-prodobo-master%3A##channel##&range=1-250&sort=startTime',
  'requestOption1' => '1',
  'accept_header1' => 'application/json',
  'content_type1' => 'application/json',
  'referer_header1' => 'https://www.magentatv.at/',
  'host_header1' => 'prod.oesp.magentatv.at',
  'origin_header1' => 'https://www.magentatv.at',
  'urldate_format1' => 'java',
  'stopdate_format1' => 'java',
  'show' => '"id":"crid:~~2F(.*?)ViaExternalApp"',
  'start' => '"startTime":(.*?),',
  'start_format' => 'java',
  'stop' => '"endTime":(.*?),',
  'stop_format' => 'java',
  'title' => '~~\\w*","title":"(.*?)","description"',
  'subtitle' => '"secondaryTitle":"(.*?)"',
  'desc' => '"longDescription":"(.*?)"',
  'category' => 'lgi-at-prodobo-master:genre-\\d*","title":"(.*?)"',
  'showicon' => '"url":"(.*?)"\\}||#max#1',
  'season' => ']"seriesNumber":"(\\d{1,3})"',
  'episode' => '"seriesEpisodeNumber":"(\\d{1,3})"',
  'channel_logo' => '||#add###cclogo##',
  'production_date' => '"year":"(.*?)"',
  'actor' => '"cast":\\["(.*?)"\\],||#split#(",")',
  'director' => '"directors":\\["(.*?)"\\],||#replace#(",")||, ',
  'rating' => '"parentalRating":"(.*?)"||#addend#+',
  'ccurl1' => 'https://prod.oesp.magentatv.at/oesp/v4/AT/deu/web/channels?byLocationId=101&includeInvisible=true&personalised=false&sort=channelNumber&withStationResolutions=SD%2CHD',
  'ccrequestOption1' => '1',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccorigin_header1' => 'https://www.magentatv.at',
  'ccchannel_block' => '\\{"id":"lgi-at-prodobo-master:\\d(.*?)"station-logo-medium"',
  'ccchannel_id' => '\\{"station":\\{"id":"lgi-at-prodobo-master:(.*?)","',
  'ccchannel_name' => '"locationId":"\\d*","title":"(.*?)","',
  'ccchannel_logo' => '"station-logo-large"],"url":"(.*?)\\?style',
);
?>