<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'sunriseupc.ch',
  'creator_name' => 'Alex',
  'creation_date' => '2022-03-25',
  'rev_no' => 'R0',
  'timezone' => '+02:00',
  'culture' => 'de',
  'max_day' => '14',
  'rating_system' => 'FSK',
  'episodeOption' => '1',
  'url1' => 'https://prod.oesp.sunriseupctv.ch/oesp/v4/CH/deu/web/listings?byEndTime=##urldate1##~&byLocationId=100&byResolutions=SD%2CHD&byStationId=lgi-ch-prod-master%3A##channel##&range=1-250&sort=startTime',
  'requestOption1' => '1',
  'accept_header1' => 'application/json',
  'content_type1' => 'application/json;charset=UTF-8',
  'referer_header1' => 'https://www.sunriseupctv.ch/',
  'host_header1' => 'prod.oesp.sunriseupctv.ch',
  'origin_header1' => 'https://www.sunriseupctv.ch',
  'custom_header1' => 'X-Client-Id: 4.34.24||Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36',
  'urldate_format1' => 'java',
  'stopdate_format1' => 'java',
  'show' => ',"star(.*?)"cloud"',
  'start' => 'tTime":(\\d{13}),"endTime"',
  'start_format' => 'java',
  'stop' => '"endTime":(\\d{13}),"',
  'stop_format' => 'java',
  'title' => '~~\\w*","title":"(.*?)","de',
  'subtitle' => '"secondaryTitle":"(.*?)"',
  'desc' => '"longDescription":"(.*?)",',
  'category' => 'genre-\\d*","title":"(.*?)",',
  'showicon' => '"HighResPortrait"],"url":"(.*?)"',
  'season' => '"seriesNumber":"(\\d{1,3})"',
  'episode' => '"seriesEpisoNumber":"(\\d{1,3})"',
  'channel_logo' => '||#add###cclogo##',
  'production_date' => ',"year":"(.*?)"',
  'actor' => '"cast":\\["(.*?)"\\]||#split#(",")',
  'director' => '"directors":\\["(.*?)"\\]||#split#(",")',
  'rating' => '"parentalRating":"(\\d*)"||#addend#+',
  'ccurl1' => 'https://prod.oesp.sunriseupctv.ch/oesp/v4/CH/deu/web/channels?byLocationId=100&includeInvisible=true&personalised=false&sort=channelNumber&withStationResolutions=SD%2CHD',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccreferer_header1' => 'https://www.sunriseupctv.ch/',
  'cchost_header1' => 'prod.oesp.sunriseupctv.ch',
  'ccorigin_header1' => 'https://www.sunriseupctv.ch',
  'ccchannel_block' => '"channelNumber":(.*?)"station-logo-medium"',
  'ccchannel_id' => '"id":"lgi-ch-prod-master:(.*?)","',
  'ccchannel_name' => '"title":"(.*?)"',
  'ccidremovedup' => 'on',
  'ccnmremovedup' => 'on',
);
?>