<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'teleboy.ch',
  'creator_name' => 'Alex',
  'creation_date' => '2022-03-25',
  'rev_no' => 'R0',
  'timezone' => '+01:00',
  'culture' => 'de',
  'max_day' => '14',
  'episodeOption' => '1',
  'url1' => 'https://tv.api.teleboy.ch/epg/broadcasts?begin=##urldate1##T00:00:00%2B01:00&end=##stopdate1##T00:00:00%2B02:00&expand=station,flags,primary_image,trailers,short_description,genre&limit=250&rangetype=begin&skip=0&station=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'content_type1' => 'application/json',
  'referer_header1' => 'https://www.teleboy.ch/',
  'origin_header1' => 'https://www.teleboy.ch',
  'custom_header1' => 'x-teleboy-apikey: e899f715940a209148f834702fc7f340b6b0496b62120b3ed9c9b3ec4d7dca00',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d',
  'show' => '"id":(.*?)"genre":',
  'start' => '"begin":"(.*?)\\+||#replace#(T)',
  'start_format' => 'Y-m-dH:i:s',
  'stop' => '"end":"(.*?)\\+||#replace#(T)',
  'stop_format' => 'Y-m-dH:i:s',
  'duration' => '"duration":(.*?),"',
  'title' => '\\+\\d*","title":"(.*?)","',
  'subtitle' => '"subtitle":"(.*?)","',
  'desc' => '"short_description":"(.*?)"',
  'category' => '"name_de":"(.*?)"',
  'season' => '"serie_season":(.*?),"',
  'episode' => '"serie_episode":(.*?),"',
  'channel_logo' => '||#add###cclogo##',
  'production_date' => '"year":(.*?),"',
  'country' => 'slug":".*"country":"(.*?)","y||#replace#Deutschland##Schweiz##Österreich##Vereinigte Staaten von Amerika##Italien##Spanien##Frankreich##Neuseeland##Australien##Schweden##Norwegen##Finnland##Dänemark##Großbritannien##China##Japan##Russland##Belgien##Niederlande##Kroatien##Rumänien##Kanada##Brasilien##Argentinien##Chile##Südafrika##Ägypten##Marokko||DE##CH##AT##USA##IT##ES##FR##NZ##AUS##SWE##NOR##FIN##DNK##GB##CN##JAP##RUS##BE##NL##KRO##ROM##CND##BRA##ARG##CHI##ZAF##EGY##MAR',
  'rating' => '"age":(\\d*),||#addend#+',
  'ccurl1' => 'https://tv.api.teleboy.ch/epg/stations?language=de',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'application/json',
  'cccustom_header1' => 'x-teleboy-apikey: e899f715940a209148f834702fc7f340b6b0496b62120b3ed9c9b3ec4d7dca00',
  'ccchannel_block' => '{"station_group(.*?),"quality":"',
  'ccchannel_id' => ',"id":(.*?),"country":"',
  'ccchannel_name' => '"country":"\\w*","name":"(.*?)","',
);
?>