<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvheute.at',
  'creator_name' => 'Alex',
  'creation_date' => '2022-10-18',
  'rev_no' => 'R0',
  'timezone' => '+01:00',
  'culture' => 'de',
  'max_day' => '14',
  'rating_system' => 'FSK',
  'episodeOption' => '1',
  'url1' => 'https://tvheute.at/##channel##-programm/##urldate1##-im-tv',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'host_header1' => 'tvheute.at',
  'custom_header1' => 'Accept-Encoding: gzip, deflate, br',
  'urldate_format1' => 'd-m-Y',
  'show' => '<a class="action-show-info(.*?)"end-col">',
  'start' => 'dates=(.*?)\\/||#replace#(T)',
  'start_format' => 'YmdHis',
  'stop' => 'dates=\\d*T\\d*\\/(.*?)&||#replace#(T)',
  'stop_format' => 'YmdHis',
  'title' => '<strong title="(.*?)"',
  'subtitle' => '\\s<span class="sub">\\w*[A-Z] (.*?), [A-Z]||#replace# \\(Staffel:.*?\\)|| ',
  'desc' => 'div class="description">(.*?)<\\/div>',
  'category' => '"sub">(\\w*) ||#word#',
  'season' => '\\(Staffel: (.*?) ',
  'episode' => 'Folge: (.*?)\\)',
  'production_date' => '\\w*(\\d{4})<',
  'country' => ', (\\w*) \\d{4}',
  'ccurl1' => 'https://tvheute.at/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cchost_header1' => 'tvheute.at',
  'cccustom_header1' => 'Accept-Encoding: gzip, deflate, br',
  'ccchannel_block' => '<li data-st(.*?)<\\/li>',
  'ccchannel_id' => 'ation="(.*?)" class',
  'ccchannel_name' => '\\/heute-im-tv">(.*?)<\\/a>',
);
?>